### ISSUE TITLE
Angular 18 Support

### ISSUE THREAD

**Issue by liamcooper** [NarikMe/narik-custom-validators#13]
Hi,

Just wondered if it was possible to upgrade this package to support Angular 18 please?

Thanks.

**Comment by javierjsp** [comment]
@liamcooper  Waiting Approve for PR #12 , @abadakhshan may you help us with that please.

**Comment by liamcooper** [comment]
> @liamcooper Waiting Approve for PR #12 , @abadakhshan may you help us with that please.

Brilliant, thank you.

**Comment by abadakhshan** [comment]
Done!
