### ISSUE TITLE
Angular 14 support needed

### ISSUE THREAD

**Issue by pkcinna01** [NarikMe/narik-custom-validators#2]

**Comment by abadakhshan** [comment]
I will upgrade to Angular 14  but let me know if you have a special problem to use this version with Angular 14?

done with https://github.com/NarikMe/narik-custom-validators/pull/3

**Comment by pkcinna01** [comment]
Thanks.  I made a fork yesterday and tried [ng update ](https://update.angular.io/?l=2&v=13.0-14.0).  I think it mostly renamed all uses of FormGroup to UntypedFormGroup.  We are also waiting on the angular-apollo client to support v14 so cannot test it yet.
